### PR TITLE
Name update

### PR DESCRIPTION
**Pull request by wittmer85**
I have changed all the code references from DGX to GBDX.  Additionally, changes extend to the names and places of logs.  The directory structure of the project has also changed to reflect the name change.

## These changes will cause the following:

- The user will have to go back through the configuration process.
- Logs are now stored in the %userprofile%\AppData\Roaming\GBDX directory
- Builds are now called Gbdx.esriaddin instead of Dgx.esriaddin

### CODE REVIEW

**Comment by christyberman** [comment]
Names have all been updated from user perspective, with exception to GBD catalog.

To keep the same format as the other tools, change name to "Catalog" instead of "GBD Data Viewer"

Also: the window name should be changed to "Catalog" instead of "GBD Dockable Window"

**Comment by wittmer85** [comment]
Changed the name of the tooltip and associated message on hover.  I also renamed the dockable window to be Catalog.

**Comment by wittmer85** [comment]
Updated build to refelct the most recent changes

**Comment by christyberman** [comment]
I'm good with this, now. Go ahead and merge.

**Pull request merged**
